{
  "hash": "696bd1a0d994caae80339df4328b77a7",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Machine Learning Classification of Center-Back Player Types in Liga MX\"\nlightbox: true\ndescription: \"Explore the similarities among center-back players in Liga MX using various machine learning and clustering methods including PCA, K-means (non-hierarchical), and Agglomerative Hierarchical Clustering\"\ndate: \"March 3, 2024\"\ncategories: \n  - R\n  - Classification \n  - Machine Learning\n  - Football\nimage: liga mx.jpg\ndraft: false\nnumber-sections: false\nformat:\n  html:\n    fig-cap-location: bottom\n    include-before-body: ../../html/margin_image.html\n    include-after-body: ../../html/blog_footer.html\neditor: \n  markdown: \n    wrap: sentence\n---\n\n\n## Introduction\n\nFútbol has been an integral part of my journey from the first time I stepped onto the field.\nThe thrill of playing as a left winger, the strategy behind every move, and the joy of scoring have deeply influenced my understanding and love for the sport.\nThis passion has seamlessly intertwined with my growing interest in analytics, leading me to explore the untapped potential of data in revealing hidden aspects of the game, such as player dynamics, strategic patterns, and performance metrics.\n\nLiga MX is more than just a league to me; it's a big part of Mexican culture.\nThe Apertura and Clausura tournaments show the excitement and spirit of Mexican soccer, bringing stories of victory and defeat that engage fans every year.\n\nIn this study, I'll concentrate on the key players in defense: the center-backs.\nTheir role, often overshadowed by the flamboyance of attackers, is crucial in orchestrating the team's defensive harmony.\nLeveraging unsupervised machine learning techniques such as Principal Component Analysis (PCA), K-means clustering, and Hierarchical Clustering, I aim to dissect and categorize the playing styles of these pivotal figures.\nEach technique serves a purpose: PCA to reduce dimensionality and highlight important performance indicators, K-means to group similar player profiles based on these indicators, and Hierarchical Clustering to build a detailed taxonomy of player types based on their on-field behavior.\n\nThis study is more than just research; it's an exploration into Liga MX using data analytics.\nBy applying these unsupervised learning methods, we will uncover the nuanced contributions of center-backs, offering new insights and appreciation for their role in the beautiful game.\nJoin me in this analytical journey, where numbers meet the pitch, and discover the unseen stories of Liga MX's defensive performances.\n\n\n\n\n\n\n\n\n\n## Data\n\nFor this research, I utilized a package tool called `worldfootballr`, which is designed to pull global football (soccer) data from platforms like FBref, Transfermarkt, Understat, and FotMob.\nThis tool helped me gather advanced statistics provided by Opta, which were then formatted into a CSV file capturing player performances throughout the Clausura 2024 regular season.\nInitially, the dataset comprised 2,428 entries across 47 different columns.\nIn the process of refining this dataset, I removed information irrelevant to our specific analysis.\nThis process also involved using a histogram shown in @fig-distribution of each player's total minutes to distinguish those who had accumulated at least 120 minutes of playtime from the start of the season until matchday 9.\n\n\n\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Distribution of Total Minutes Played](index_files/figure-html/fig-distribution-1.png){#fig-distribution width=672}\n:::\n:::\n\n\nAfter these adjustments, the final dataset presented 57 unique center-back players alongside 15 variable features.\nEach record within this dataset corresponds to an individual player, encompassing important performance data from the season, such as the number of tackles made, tackles within the defensive third, and instances of lost challenges.\nBelow in @tbl-data are the first 6 observations:\n\n\n::: {#tbl-data .cell tbl-cap='Clean Dataset'}\n::: {.cell-output-display}\n\n\n| Tkl_Tackles| TklW_Tackles| Def 3rd_Tackles| Mid 3rd_Tackles| Att 3rd_Tackles| Tkl_Challenges| Att_Challenges| Lost_Challenges| Blocks_Blocks| Sh_Blocks| Pass_Blocks|  Int| Tkl+Int|  Clr| Err|\n|-----------:|------------:|---------------:|---------------:|---------------:|--------------:|--------------:|---------------:|-------------:|---------:|-----------:|----:|-------:|----:|---:|\n|        2.11|         1.22|            1.33|            0.78|               0|           1.00|           1.44|            0.44|          1.11|      0.89|        0.22| 1.44|    3.56| 4.00|   0|\n|        1.44|         1.11|            1.11|            0.33|               0|           1.22|           1.33|            0.11|          1.22|      0.33|        0.89| 0.89|    2.33| 6.78|   0|\n|        2.11|         1.33|            1.67|            0.44|               0|           1.22|           1.78|            0.56|          1.56|      1.00|        0.56| 2.22|    4.33| 6.00|   0|\n|        2.00|         1.29|            1.86|            0.14|               0|           0.71|           1.00|            0.29|          1.43|      0.71|        0.71| 0.86|    2.86| 3.57|   0|\n|        2.33|         1.00|            1.67|            0.67|               0|           2.00|           3.33|            1.33|          0.33|      0.33|        0.00| 2.67|    5.00| 1.67|   0|\n|        0.33|         0.22|            0.22|            0.11|               0|           0.11|           0.11|            0.00|          0.56|      0.44|        0.11| 0.56|    0.89| 2.89|   0|\n\n\n:::\n:::\n\n\n\n\nBelow in @tbl-variables are the description of each variable used for the analysis:\n\n\n::: {#tbl-variables .cell tbl-cap='Summary of Variables in Dataset'}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"tngayenxai\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#tngayenxai table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#tngayenxai thead, #tngayenxai tbody, #tngayenxai tfoot, #tngayenxai tr, #tngayenxai td, #tngayenxai th {\n  border-style: none;\n}\n\n#tngayenxai p {\n  margin: 0;\n  padding: 0;\n}\n\n#tngayenxai .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#tngayenxai .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#tngayenxai .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#tngayenxai .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#tngayenxai .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#tngayenxai .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#tngayenxai .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#tngayenxai .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#tngayenxai .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#tngayenxai .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#tngayenxai .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#tngayenxai .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#tngayenxai .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#tngayenxai .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#tngayenxai .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#tngayenxai .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#tngayenxai .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#tngayenxai .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#tngayenxai .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tngayenxai .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#tngayenxai .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#tngayenxai .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#tngayenxai .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tngayenxai .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#tngayenxai .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#tngayenxai .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#tngayenxai .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tngayenxai .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#tngayenxai .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#tngayenxai .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#tngayenxai .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#tngayenxai .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#tngayenxai .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tngayenxai .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#tngayenxai .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tngayenxai .gt_left {\n  text-align: left;\n}\n\n#tngayenxai .gt_center {\n  text-align: center;\n}\n\n#tngayenxai .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#tngayenxai .gt_font_normal {\n  font-weight: normal;\n}\n\n#tngayenxai .gt_font_bold {\n  font-weight: bold;\n}\n\n#tngayenxai .gt_font_italic {\n  font-style: italic;\n}\n\n#tngayenxai .gt_super {\n  font-size: 65%;\n}\n\n#tngayenxai .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#tngayenxai .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#tngayenxai .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#tngayenxai .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#tngayenxai .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#tngayenxai .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#tngayenxai .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#tngayenxai .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#tngayenxai div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;div data-qmd-base64=&quot;KipWYXJpYWJsZXMqKg==&quot;&gt;&lt;div class='gt_from_md'&gt;&lt;p&gt;&lt;strong&gt;Variables&lt;/strong&gt;&lt;/p&gt;&#10;&lt;/div&gt;&lt;/div&gt;\"><div data-qmd-base64=\"KipWYXJpYWJsZXMqKg==\"><div class='gt_from_md'><p><strong>Variables</strong></p>\n</div></div></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;div data-qmd-base64=&quot;KipEZXNjcmlwdGlvbioq&quot;&gt;&lt;div class='gt_from_md'&gt;&lt;p&gt;&lt;strong&gt;Description&lt;/strong&gt;&lt;/p&gt;&#10;&lt;/div&gt;&lt;/div&gt;\"><div data-qmd-base64=\"KipEZXNjcmlwdGlvbioq\"><div class='gt_from_md'><p><strong>Description</strong></p>\n</div></div></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"variables\" class=\"gt_row gt_left\">Tkl_Tackles</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Number of players tackled</td></tr>\n    <tr><td headers=\"variables\" class=\"gt_row gt_left\">TklW_Tackles</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Tackles in which the tackler's team won possession of the ball</td></tr>\n    <tr><td headers=\"variables\" class=\"gt_row gt_left\">Def 3rd_Tackles</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Tackles in defensive 1/3</td></tr>\n    <tr><td headers=\"variables\" class=\"gt_row gt_left\">Mid 3rd_Tackles</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Tackles in middle 1/3</td></tr>\n    <tr><td headers=\"variables\" class=\"gt_row gt_left\">Att 3rd_Tackles</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Tackles in attacking 1/3</td></tr>\n    <tr><td headers=\"variables\" class=\"gt_row gt_left\">Tkl_Challenges</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Number of dribblers tackled</td></tr>\n    <tr><td headers=\"variables\" class=\"gt_row gt_left\">Att_Challenges</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Number of unsuccessful challenges plus number of dribblers tackled</td></tr>\n    <tr><td headers=\"variables\" class=\"gt_row gt_left\">Lost_Challenges</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Number of unsucessful attempts to challenge a dribbling player</td></tr>\n    <tr><td headers=\"variables\" class=\"gt_row gt_left\">Blocks_Blocks</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Number of times blocking the ball by standing in its path</td></tr>\n    <tr><td headers=\"variables\" class=\"gt_row gt_left\">Sh_Blocks</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Number of times blocking a shot by standing in its path</td></tr>\n    <tr><td headers=\"variables\" class=\"gt_row gt_left\">Pass_Blocks</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Number of times blocking a pass by standing in its path</td></tr>\n    <tr><td headers=\"variables\" class=\"gt_row gt_left\">Int</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Interceptions</td></tr>\n    <tr><td headers=\"variables\" class=\"gt_row gt_left\">Tkl+Int</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Number of players tackled plus number of interceptions</td></tr>\n    <tr><td headers=\"variables\" class=\"gt_row gt_left\">Clr</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Clearances</td></tr>\n    <tr><td headers=\"variables\" class=\"gt_row gt_left\">Err</td>\n<td headers=\"description\" class=\"gt_row gt_left\">Mistakes leading to an opponent's shot</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n## Principal Component Analysis (PCA)\n\nPrincipal component analysis aims to describe the variance-covariance relationship among a group of variables by using a small number of linear combinations of these variables.\nThe primary goals are to reduce the dimensionality of the data and to provide an interpretation through the rotation process.\n\nAlgebraically, principal components are unique linear combinations of the p random variables $X_1,X_2,\\ldots,X_p$.\nGeometrically, this translates to forming a new set of axes through the rotation of the original coordinate system, where $X_1,X_2,\\ldots,X_p$ are the axes.\nThese newly established axes stand for the most significant variation directions, simplifying and condensing the description of the covariance matrix.\n\nLet the random vector $X' = [X_1,X_2,\\dots,X_p]$ have the covariance matrix $\\Sigma$ with eigenvalues $\\lambda_1 \\geq \\lambda_2 \\geq \\ldots \\geq \\lambda_p = 0$.\n\nConsider the linear combinations \\begin{align*}\nY_1 &= \\boldsymbol{a'_1X} =  a_{11}X_1 + a_{12}X_2 +\\ldots+ a_{1p}X_p \\\\\nY_2 &= \\boldsymbol{a'_2X} =  a_{21}X_1 + a_{22}X_2 +\\ldots+ a_{2p}X_p \\\\\n&\\vdots\\\\\nY_p &= \\boldsymbol{a'_pX} =  a_{p1}X_1 + a_{p2}X_2 +\\ldots+ a_{pp}X_p\n\\end{align*}\n\nThen, we obtain \\begin{align*}\n\\text{Var}(Y_i) &= \\boldsymbol{a'_i\\Sigma a_i} \\qquad &i = 1,2,...,p \\\\\n\\text{Cov}(Y_i,Y_k) &= \\boldsymbol{a'_i\\Sigma a_k} \\qquad &i,k = 1,2,\\ldots,p\n\\end{align*}\n\nThe principal components are distinct linear combinations formed from the original variables, designed to be independent of each other.\n\nThe first principal component is the linear combination with maximum variance.\nThat is, it maximizes $\\text{Var}(Y_1) = \\boldsymbol{a'_i\\Sigma a_i}$.\nIt is clear that $\\text{Var}(Y_1) = \\boldsymbol{a'_i\\Sigma a_i}$ can be increased by multiplying any $\\boldsymbol{a_1}$ by some constant.\nTo eliminate this indeterminacy, it is convenient to restrict attention to coefficient vectors of unit length.\nWe therefore define\n\n\n```{=tex}\n\\begin{align*}\n\\text{First principal component} =\\ &\\text{linear combination}\\ \\boldsymbol{a'_1X}\\ \\text{that maximizes} \\\\ \n&\\text{Var}(\\boldsymbol{a'_1X})\\ \\text{subject to a}\\ \\boldsymbol{a'_1a_1} = 1\n\\end{align*}\n```\n\n```{=tex}\n\\begin{align*}\n\\text{Second principal component} =\\ &\\text{linear combination}\\ \\boldsymbol{a'_2X}\\ \\text{that maximizes} \\\\ \n&\\text{Var}(\\boldsymbol{a'_2X})\\ \\text{subject to a}\\ \\boldsymbol{a'_2a_2} = 1\\ \\text{and} \\\\\n&\\text{Cov}(\\boldsymbol{a'_1X,a'_2X}) = 0\n\\end{align*}\n```\n\nAt the $i$th step, \\begin{align*}\ni\\text{th principal component} =\\ &\\text{linear combination}\\ \\boldsymbol{a'_iX}\\ \\text{that maximizes} \\\\ \n&\\text{Var}(\\boldsymbol{a'_iX})\\ \\text{subject to a}\\ \\boldsymbol{a'_ia_i} = 1\\ \\text{and} \\\\\n&\\text{Cov}(\\boldsymbol{a'_iX,a'_kX}) = 0\\ \\text{for}\\ k < i\n\\end{align*}\n\nInitially, the data is scaled to normalize the scale of each variable.\nThis ensures that all variables contribute equally to the analysis.\nThis standardization process is crucial and is mathematically represented as,\n\n\n```{=tex}\n\\begin{align*}\nZ_1 &= \\frac{(X_1 - \\mu_1)}{\\sqrt{\\sigma_{11}}} \\\\\nZ_2 &= \\frac{(X_2 - \\mu_2)}{\\sqrt{\\sigma_{22}}} \\\\\n&\\vdots\\\\\nZ_p &= \\frac{(X_p - \\mu_p)}{\\sqrt{\\sigma_{pp}}}\n\\end{align*}\n```\n\nIn matrix form, \\begin{align*}\n\\boldsymbol{Z} = (\\boldsymbol{V}^{1/2})^{-1}(\\boldsymbol{X} - \\boldsymbol{\\mu})\n\\end{align*}\n\nwhere the diagonal standard deviation matrix is $\\boldsymbol{V}^{1/2}$.\n\nAfter standardizing the data, we compute its covariance matrix to examine the relationships among the variables, which is mathematically represented as:\n\n\n```{=tex}\n\\begin{align*}\n\\text{Cov}(\\boldsymbol{Z}) = (\\boldsymbol{V}^{1/2})^{-1}\\boldsymbol{\\Sigma}(\\boldsymbol{V}^{1/2})^{-1} = \\boldsymbol{\\rho}\n\\end{align*}\n```\n\nIn this formula, $\\boldsymbol{\\rho}$ denotes the correlation matrix of the original variables $\\boldsymbol{X}$, after transformation into the standardized form $\\boldsymbol{Z}$.\nThis step is crucial for understanding how variables relate to one another in the scaled space.\nFollowing this, we determine the eigenvalues and eigenvectors from this correlation matrix, $\\boldsymbol{\\rho}$.\nThe eigenvalues quantify the amount of variance each principal component captures, while the eigenvectors specify the directional orientation of these components, providing insight into the underlying structure of the data.\n\nThe standardized data is shown below in @tbl-scaled:\n\n\n::: {#tbl-scaled .cell tbl-cap='Standardized Dataset'}\n::: {.cell-output-display}\n\n\n|                      | Tkl_Tackles| TklW_Tackles| Def 3rd_Tackles| Mid 3rd_Tackles| Att 3rd_Tackles| Tkl_Challenges| Att_Challenges| Lost_Challenges| Blocks_Blocks| Sh_Blocks| Pass_Blocks|   Int| Tkl+Int|   Clr|   Err|\n|:---------------------|-----------:|------------:|---------------:|---------------:|---------------:|--------------:|--------------:|---------------:|-------------:|---------:|-----------:|-----:|-------:|-----:|-----:|\n|Adonis Frías          |        1.08|         0.77|            0.74|            1.39|           -0.55|           0.69|           0.44|            0.03|          0.14|      0.57|       -0.53|  0.34|    0.90|  0.42| -0.34|\n|Alexis Francisco Peña |        0.08|         0.53|            0.34|           -0.36|           -0.55|           1.19|           0.29|           -0.84|          0.34|     -0.73|        1.54| -0.54|   -0.27|  2.48| -0.34|\n|Alán Montes           |        1.08|         1.01|            1.36|            0.06|           -0.55|           1.19|           0.92|            0.35|          0.97|      0.82|        0.52|  1.59|    1.63|  1.90| -0.34|\n|Anderson Santamaría   |        0.92|         0.92|            1.71|           -1.10|           -0.55|           0.03|          -0.17|           -0.36|          0.73|      0.15|        0.98| -0.59|    0.23|  0.10| -0.34|\n|Andres Micolta Arroyo |        1.41|         0.29|            1.36|            0.96|           -0.55|           2.97|           3.08|            2.39|         -1.31|     -0.73|       -1.21|  2.32|    2.26| -1.30| -0.34|\n|Antonio Briseño       |       -1.57|        -1.41|           -1.27|           -1.22|           -0.55|          -1.33|          -1.41|           -1.13|         -0.88|     -0.47|       -0.87| -1.08|   -1.63| -0.40| -0.34|\n\n\n:::\n:::\n\n\nIn our analysis, we specifically focus on the loadings of the first two principal components.\nThese loadings reflect how each original variable contributes to the formation of the principal components.\nBy analyzing the loadings of the first two components, we gain insights into the most significant patterns and variations within the data.\n\nThe mathematical approach of the $i$th principal component of the standardized variables $\\boldsymbol{Z}' = [Z_1,Z_2,\\ldots,Z_p]$ with $\\text{Cov}(\\boldsymbol{Z}) = \\boldsymbol{\\rho}$ is represented as:\n\n\n```{=tex}\n\\begin{align*}\n\\boldsymbol{Y_i}' = \\boldsymbol{{e_i{Z}}} = \\boldsymbol{e'_{i}}(\\boldsymbol{V}^{1/2})^{-1}(\\boldsymbol{X}-\\boldsymbol{\\mu}), \\qquad i = 1,2,\\ldots,p\n\\end{align*}\n```\n\nThe loadings for the first and second principal components, denoted as PC1 and PC2 respectively, are presented below in @tbl-loadings:\n\n\n::: {#tbl-loadings .cell tbl-cap='Variable PCA Loadings: PC1 and PC2 Analysis'}\n\n```{.r .cell-code  code-fold=\"true\"}\ncov_df <- cov(scaled_df)\neigen_df <- eigen(cov_df)\n\nphi <- eigen_df$vectors[,1:2]\n\nrow.names(phi) <- colnames(clean_df)\ncolnames(phi) <- c(\"PC 1\", \"PC 2\")\n\nphi %>%\n  knitr::kable(digits = 2)\n```\n\n::: {.cell-output-display}\n\n\n|                |  PC 1|  PC 2|\n|:---------------|-----:|-----:|\n|Tkl_Tackles     | -0.37| -0.12|\n|TklW_Tackles    | -0.33| -0.07|\n|Def 3rd_Tackles | -0.34| -0.06|\n|Mid 3rd_Tackles | -0.23| -0.13|\n|Att 3rd_Tackles |  0.01| -0.27|\n|Tkl_Challenges  | -0.33| -0.27|\n|Att_Challenges  | -0.33| -0.20|\n|Lost_Challenges | -0.26| -0.07|\n|Blocks_Blocks   | -0.20|  0.55|\n|Sh_Blocks       | -0.11|  0.54|\n|Pass_Blocks     | -0.18|  0.19|\n|Int             | -0.20|  0.10|\n|Tkl+Int         | -0.36| -0.02|\n|Clr             | -0.19|  0.35|\n|Err             | -0.08|  0.06|\n\n\n:::\n:::\n\n\nThe total variance for the standardized variables in the population is equal to $p$, which represents the sum of the diagonal elements of the matrix, also known as the trace of the correlation matrix $\\boldsymbol{\\rho}$.\nConsequently, the fraction of the total variance accounted for by the $k$th principal component of $\\boldsymbol{Z}$ is determined as follows:\n\n$$\n\\begin{pmatrix}\n\\text{Proportion of (standardized)}\\\\\n\\text{population variance due}\\\\\n\\text{to}\\ k\\text{th principal component}\n\\end{pmatrix} = \\frac{\\lambda_k}{p}, \\qquad k = 1,2,\\ldots,p\n$$ where the $\\lambda_k's$ are the eigenvalues of $\\boldsymbol{\\rho}$.\n\nThe Proportion of Variance for each Principal Component (PC) is presented below in @tbl-prop_var:\n\n\n::: {#tbl-prop_var .cell tbl-cap='Proportion of Variance'}\n\n```{.r .cell-code  code-fold=\"true\"}\nsum_cov <- sum(diag(cov(scaled_df)))\nresults <- eigen_df$values/sum_cov \n\nprop_var <- tibble(\n  principal_components = paste0(\"PC \", 1:15),\n  results = results\n)\n\nprop_var %>%\n  gt() %>%\n  cols_label(\n    principal_components = md(\"**Principal Components**\"),\n    results = md(\"**Results**\")\n  ) %>%\n  fmt_number(\n    columns = results,\n    decimals = 2\n  ) %>%\n  opt_table_font(\n    google_font(name = \"Roboto\")\n  ) %>%\n  tab_options(data_row.padding = px(1))\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"csrmcoxmgn\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>@import url(\"https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap\");\n#csrmcoxmgn table {\n  font-family: Roboto, system-ui, 'Segoe UI', Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#csrmcoxmgn thead, #csrmcoxmgn tbody, #csrmcoxmgn tfoot, #csrmcoxmgn tr, #csrmcoxmgn td, #csrmcoxmgn th {\n  border-style: none;\n}\n\n#csrmcoxmgn p {\n  margin: 0;\n  padding: 0;\n}\n\n#csrmcoxmgn .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#csrmcoxmgn .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#csrmcoxmgn .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#csrmcoxmgn .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#csrmcoxmgn .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#csrmcoxmgn .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#csrmcoxmgn .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#csrmcoxmgn .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#csrmcoxmgn .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#csrmcoxmgn .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#csrmcoxmgn .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#csrmcoxmgn .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#csrmcoxmgn .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#csrmcoxmgn .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#csrmcoxmgn .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#csrmcoxmgn .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#csrmcoxmgn .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#csrmcoxmgn .gt_row {\n  padding-top: 1px;\n  padding-bottom: 1px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#csrmcoxmgn .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#csrmcoxmgn .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#csrmcoxmgn .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#csrmcoxmgn .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#csrmcoxmgn .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#csrmcoxmgn .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#csrmcoxmgn .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#csrmcoxmgn .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#csrmcoxmgn .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#csrmcoxmgn .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#csrmcoxmgn .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#csrmcoxmgn .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#csrmcoxmgn .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#csrmcoxmgn .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#csrmcoxmgn .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#csrmcoxmgn .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#csrmcoxmgn .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#csrmcoxmgn .gt_left {\n  text-align: left;\n}\n\n#csrmcoxmgn .gt_center {\n  text-align: center;\n}\n\n#csrmcoxmgn .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#csrmcoxmgn .gt_font_normal {\n  font-weight: normal;\n}\n\n#csrmcoxmgn .gt_font_bold {\n  font-weight: bold;\n}\n\n#csrmcoxmgn .gt_font_italic {\n  font-style: italic;\n}\n\n#csrmcoxmgn .gt_super {\n  font-size: 65%;\n}\n\n#csrmcoxmgn .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#csrmcoxmgn .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#csrmcoxmgn .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#csrmcoxmgn .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#csrmcoxmgn .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#csrmcoxmgn .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#csrmcoxmgn .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#csrmcoxmgn .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#csrmcoxmgn div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;div data-qmd-base64=&quot;KipQcmluY2lwYWwgQ29tcG9uZW50cyoq&quot;&gt;&lt;div class='gt_from_md'&gt;&lt;p&gt;&lt;strong&gt;Principal Components&lt;/strong&gt;&lt;/p&gt;&#10;&lt;/div&gt;&lt;/div&gt;\"><div data-qmd-base64=\"KipQcmluY2lwYWwgQ29tcG9uZW50cyoq\"><div class='gt_from_md'><p><strong>Principal Components</strong></p>\n</div></div></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;div data-qmd-base64=&quot;KipSZXN1bHRzKio=&quot;&gt;&lt;div class='gt_from_md'&gt;&lt;p&gt;&lt;strong&gt;Results&lt;/strong&gt;&lt;/p&gt;&#10;&lt;/div&gt;&lt;/div&gt;\"><div data-qmd-base64=\"KipSZXN1bHRzKio=\"><div class='gt_from_md'><p><strong>Results</strong></p>\n</div></div></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"principal_components\" class=\"gt_row gt_left\">PC 1</td>\n<td headers=\"results\" class=\"gt_row gt_right\">0.43</td></tr>\n    <tr><td headers=\"principal_components\" class=\"gt_row gt_left\">PC 2</td>\n<td headers=\"results\" class=\"gt_row gt_right\">0.13</td></tr>\n    <tr><td headers=\"principal_components\" class=\"gt_row gt_left\">PC 3</td>\n<td headers=\"results\" class=\"gt_row gt_right\">0.10</td></tr>\n    <tr><td headers=\"principal_components\" class=\"gt_row gt_left\">PC 4</td>\n<td headers=\"results\" class=\"gt_row gt_right\">0.08</td></tr>\n    <tr><td headers=\"principal_components\" class=\"gt_row gt_left\">PC 5</td>\n<td headers=\"results\" class=\"gt_row gt_right\">0.07</td></tr>\n    <tr><td headers=\"principal_components\" class=\"gt_row gt_left\">PC 6</td>\n<td headers=\"results\" class=\"gt_row gt_right\">0.07</td></tr>\n    <tr><td headers=\"principal_components\" class=\"gt_row gt_left\">PC 7</td>\n<td headers=\"results\" class=\"gt_row gt_right\">0.05</td></tr>\n    <tr><td headers=\"principal_components\" class=\"gt_row gt_left\">PC 8</td>\n<td headers=\"results\" class=\"gt_row gt_right\">0.03</td></tr>\n    <tr><td headers=\"principal_components\" class=\"gt_row gt_left\">PC 9</td>\n<td headers=\"results\" class=\"gt_row gt_right\">0.02</td></tr>\n    <tr><td headers=\"principal_components\" class=\"gt_row gt_left\">PC 10</td>\n<td headers=\"results\" class=\"gt_row gt_right\">0.02</td></tr>\n    <tr><td headers=\"principal_components\" class=\"gt_row gt_left\">PC 11</td>\n<td headers=\"results\" class=\"gt_row gt_right\">0.01</td></tr>\n    <tr><td headers=\"principal_components\" class=\"gt_row gt_left\">PC 12</td>\n<td headers=\"results\" class=\"gt_row gt_right\">0.00</td></tr>\n    <tr><td headers=\"principal_components\" class=\"gt_row gt_left\">PC 13</td>\n<td headers=\"results\" class=\"gt_row gt_right\">0.00</td></tr>\n    <tr><td headers=\"principal_components\" class=\"gt_row gt_left\">PC 14</td>\n<td headers=\"results\" class=\"gt_row gt_right\">0.00</td></tr>\n    <tr><td headers=\"principal_components\" class=\"gt_row gt_left\">PC 15</td>\n<td headers=\"results\" class=\"gt_row gt_right\">0.00</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\nNow, the proportion of total variance explained by the first and second principal components is calculated as the sum of the first eigenvalue divided by the total variance plus the second eigenvalue divided by the total variance, represented as:\n\n\n```{=tex}\n\\begin{align*}\n(\\frac{\\lambda_{1} + \\lambda_{2}}{p})100\\% = (\\frac{6.376 + 1.960}{15})100\\% = 55.6\\%\n\\end{align*}\n```\n\nof the total (standardized) variance, have interesting interpretations.\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\ntotal_prop_var <- (eigen_df$values[1] + eigen_df$values[2]) / sum_cov\n\nprint(paste0(\"Total variance explained by PC1 and PC2: \", round(total_prop_var, 4) * 100, \"%\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Total variance explained by PC1 and PC2: 55.58%\"\n```\n\n\n:::\n:::\n\n\nThe PCA scores for each player, as shown below in @tbl-scores, represent the coordinates of each player in the space defined by the first two principal components (PC1 and PC2).\nThese scores are calculated based on the original data transformed by the respective principal component loadings.\n\n\n::: {#tbl-scores .cell tbl-cap='Player PCA Scores: PC1 and PC2 Analysis'}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"ywimzzzypw\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>@import url(\"https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap\");\n#ywimzzzypw table {\n  font-family: Roboto, system-ui, 'Segoe UI', Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#ywimzzzypw thead, #ywimzzzypw tbody, #ywimzzzypw tfoot, #ywimzzzypw tr, #ywimzzzypw td, #ywimzzzypw th {\n  border-style: none;\n}\n\n#ywimzzzypw p {\n  margin: 0;\n  padding: 0;\n}\n\n#ywimzzzypw .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#ywimzzzypw .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#ywimzzzypw .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#ywimzzzypw .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#ywimzzzypw .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ywimzzzypw .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ywimzzzypw .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ywimzzzypw .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#ywimzzzypw .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#ywimzzzypw .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#ywimzzzypw .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#ywimzzzypw .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#ywimzzzypw .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#ywimzzzypw .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#ywimzzzypw .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ywimzzzypw .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#ywimzzzypw .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#ywimzzzypw .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#ywimzzzypw .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ywimzzzypw .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#ywimzzzypw .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#ywimzzzypw .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#ywimzzzypw .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ywimzzzypw .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#ywimzzzypw .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#ywimzzzypw .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ywimzzzypw .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ywimzzzypw .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#ywimzzzypw .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ywimzzzypw .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#ywimzzzypw .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ywimzzzypw .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ywimzzzypw .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ywimzzzypw .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ywimzzzypw .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ywimzzzypw .gt_left {\n  text-align: left;\n}\n\n#ywimzzzypw .gt_center {\n  text-align: center;\n}\n\n#ywimzzzypw .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#ywimzzzypw .gt_font_normal {\n  font-weight: normal;\n}\n\n#ywimzzzypw .gt_font_bold {\n  font-weight: bold;\n}\n\n#ywimzzzypw .gt_font_italic {\n  font-style: italic;\n}\n\n#ywimzzzypw .gt_super {\n  font-size: 65%;\n}\n\n#ywimzzzypw .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#ywimzzzypw .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#ywimzzzypw .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#ywimzzzypw .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#ywimzzzypw .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#ywimzzzypw .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#ywimzzzypw .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#ywimzzzypw .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#ywimzzzypw div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"Player\">Player</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"Team\">Team</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"PC1\">PC1</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" style=\"font-weight: bold;\" scope=\"col\" id=\"PC2\">PC2</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Player\" class=\"gt_row gt_left\">Adonis Frías</td>\n<td headers=\"Team\" class=\"gt_row gt_left\">León</td>\n<td headers=\"PC1\" class=\"gt_row gt_center\">−2.05</td>\n<td headers=\"PC2\" class=\"gt_row gt_center\">−0.10</td></tr>\n    <tr><td headers=\"Player\" class=\"gt_row gt_left\">Alexis Francisco Peña</td>\n<td headers=\"Team\" class=\"gt_row gt_left\">Necaxa</td>\n<td headers=\"PC1\" class=\"gt_row gt_center\">−1.03</td>\n<td headers=\"PC2\" class=\"gt_row gt_center\">0.69</td></tr>\n    <tr><td headers=\"Player\" class=\"gt_row gt_left\">Alán Montes</td>\n<td headers=\"Team\" class=\"gt_row gt_left\">Necaxa</td>\n<td headers=\"PC1\" class=\"gt_row gt_center\">−3.63</td>\n<td headers=\"PC2\" class=\"gt_row gt_center\">1.18</td></tr>\n    <tr><td headers=\"Player\" class=\"gt_row gt_left\">Anderson Santamaría</td>\n<td headers=\"Team\" class=\"gt_row gt_left\">Atlas</td>\n<td headers=\"PC1\" class=\"gt_row gt_center\">−1.13</td>\n<td headers=\"PC2\" class=\"gt_row gt_center\">0.69</td></tr>\n    <tr><td headers=\"Player\" class=\"gt_row gt_left\">Andres Micolta Arroyo</td>\n<td headers=\"Team\" class=\"gt_row gt_left\">Pachuca</td>\n<td headers=\"PC1\" class=\"gt_row gt_center\">−4.36</td>\n<td headers=\"PC2\" class=\"gt_row gt_center\">−3.45</td></tr>\n    <tr><td headers=\"Player\" class=\"gt_row gt_left\">Antonio Briseño</td>\n<td headers=\"Team\" class=\"gt_row gt_left\">Guadalajara</td>\n<td headers=\"PC1\" class=\"gt_row gt_center\">4.25</td>\n<td headers=\"PC2\" class=\"gt_row gt_center\">0.25</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n##### Scores For Each Player\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Individuals - PCA](index_files/figure-html/fig-plot-1.png){#fig-plot width=672}\n:::\n:::\n\n\n@fig-plot indicates the presence of two outliers, specifically players Guido Pizarro from Tigres UANL and Andres Micolta Arroyo from CF Pachuca.\nWe will examine the impact of these outliers on the clustering process in subsequent steps.\n\n::: callout-tip\n## Principal Component Analysis with `prcomp` Function\n\nR offers an easy method for data analysis with its builtin `prcomp` function, used for Principal Component Analysis.\nIf you set `scale = TRUE`, it standardizes the data automatically.\nThis function provides principal components and their impact on variance.\nThe summary given by the function shows detailed variance information for each component, making it easier to understand and reduce complex data.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\npca_df <- prcomp(clean_df, scale = TRUE)\n\nsummary(pca_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nImportance of components:\n                          PC1    PC2     PC3     PC4     PC5    PC6     PC7\nStandard deviation     2.5251 1.4001 1.19456 1.08645 1.04146 1.0188 0.84045\nProportion of Variance 0.4251 0.1307 0.09513 0.07869 0.07231 0.0692 0.04709\nCumulative Proportion  0.4251 0.5558 0.65090 0.72959 0.80190 0.8711 0.91819\n                           PC8     PC9    PC10    PC11    PC12     PC13\nStandard deviation     0.69325 0.57368 0.53408 0.36360 0.00566 0.005024\nProportion of Variance 0.03204 0.02194 0.01902 0.00881 0.00000 0.000000\nCumulative Proportion  0.95022 0.97217 0.99118 0.99999 1.00000 1.000000\n                           PC14     PC15\nStandard deviation     0.003521 0.002493\nProportion of Variance 0.000000 0.000000\nCumulative Proportion  1.000000 1.000000\n```\n\n\n:::\n:::\n\n\nThe summary indicates that the initial principal components, particularly PC1 and PC2, play significant roles in capturing the dataset's variance, with PC1 alone accounting for 42.51% and PC2 adding another 13.07%.\nThis showcases their importance in representing the dataset's structure.\nAs more components are added, the cumulative variance explained increases, reaching virtually 100% by PC12, which suggests that the components beyond this point have minimal impact on explaining additional variance.\nThat means that when $\\rho$ is near 1, the last $\\rho - 1$ components collectively contribute very little to the total variance and can often be neglected.\nTherefore, focusing on the first few components is essential for effective dimensionality reduction and dataset interpretation, while the latter components can generally be omitted from further analysis.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Scree Plot](index_files/figure-html/fig-screeplot-1.png){#fig-screeplot width=672}\n:::\n:::\n\n\nThe *scree plot* in @fig-screeplot above is a useful visual aid to determining an appropriate number of principal components.\nThe first principal component explain 42.51% of the total variance.\nThe first two principal components, collectively, explain 55.58% of the total variance.\nAn elbow occurs at about $i = 3$.\nThat is, the eigenvalues after $\\lambda_2$ are all relatively small and about the same size.\nIn this case, it appears, without any other evidence, that two sample principal components effectively summarize the total variance of the data.\n\n##### Contributions of variables to PCs\n\nThe key variables, which contribute most significantly, can be emphasized in the correlation plot as follows:\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Variables - PCA](index_files/figure-html/fig-variables-1.png){#fig-variables width=672}\n:::\n:::\n\n\nAll the variables grouped together @fig-variables, such as `Tkl+Int`, `Def_3rd_Tackles`, `Tkl_Tackles`, `Att_3rd_Tackles`, `TklW_Tackles`, `Tkl_Challenges`, `Mid_3rd_Tackles`, `Att_Challenges`, and `Lost_Challenges` are positively correlated with each other.\nThis positive correlation is due to their proximity to each other and their downward direction.\nConversely, `Sh_Blocks`, `Blocks_Blocks`, and `Clr` are grouped together and show a positive correlation, as their vectors point upwards.\nThis indicates that these two sets of variables move in opposite directions, meaning they are negatively correlated.\nNegatively correlated variables are positioned on opposite sides of the plot's origin, in opposed quadrants.\nThe distance between variables and the origin measures how well the variables are represented on the factor map; those further from the origin are better represented.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\nThis bar plot displays the contributions of various variables to PC1 (dim1) on the left and to PC2 (dim2) on the right.\nThe red dashed line across the graph represents the expected average contribution for each dimension.\n\n##### Biplot\n\nIn the biplot, individual player scores are plotted alongside variables, allowing for a comprehensive visual representation of their performances in relation to the different measured factors.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Contributions of Individual Scores and Variables to PCs](index_files/figure-html/fig-varscores-1.png){#fig-varscores width=672}\n:::\n:::\n\n\nIn this biplot analysis plot from @fig-varscores, it's crucial to understand that a player's position relative to a specific variable indicates their performance in that area.\nPlayers on the same side as a variable typically exhibit high values for that trait, while those on the opposite side represent lower values.\nFor instance, several players located in the third quadrant, where most Dim1 contributing variables are present, demonstrate significant defensive actions.\nSebastian Olmedo from Club Puebla, notable for his high Dim1 representation, exemplifies a player actively involved in defense.\nSimilarly, players like Arturo Ortiz, who are positioned close to Olmedo, share these defensive characteristics, forming a group identified as traditional old-school defenders.\n\nConversely, in the second quadrant, opposite the traditional defenders, we find variables negatively correlated with defensive actions, such as `Blocks_Blocks`, `Sh_Blocks`, and `Clr`.\nSantiago Nunez of Santos Laguna stands out here as a \"stopper,\" excelling in blocking, indicative of a different defensive skill set.\n\nAdditionally, outliers like Andres Micolta Arroyo from C.F.\nPachuca and Guido Pizarro from Tigres UANL are positioned apart from clusters, suggesting unique styles of play that, while distinct, significantly impact the game by contributing to key variables.\n\nLastly, there's a distinct group known as `Att.3rd_tackles` players, including Diego de Buen from Club Puebla and Ventura Alvarado from Mazatlan F.C. These individuals specialize in stopping counter-attacks and play a crucial role during 'el balón parado' situations, as they call it in Spanish, which refers to set pieces or moments when the ball is stationary.\nTheir positioning in the biplot underscores their expertise in initiating defensive maneuvers during these pivotal moments of the game.\n\n## Non-Hierarchical Clustering\n\n### K-Means Clustering\n\nFollowing the PCA analysis, we will now proceed with K-means clustering to further explore our dataset.\nThis method will allow us to categorize the data into distinct groups based on similarities identified during the PCA.\nBy applying K-means clustering, we aim to enhance our understanding of the underlying structures and relationships within the data, facilitating more targeted interpretations and insights.\nThis step is crucial in identifying natural groupings among players or variables, leading to more nuanced conclusions and strategic decisions.\n\n**A Focus on Euclidean Distance:** An essential step in K-means clustering involves discussing the dissimilarity or distance measurement within the data.\nIn our analysis, we opt for the Euclidean distance, which is the standard method for K-means and measures the straight-line distance between points in multidimensional space.\nThis choice is due to its simplicity and effectiveness in quantifying the dissimilarity between data points.\nBy utilizing Euclidean distance, we can ensure that the clusters formed are based on the actual spatial differences among data points, making it a suitable and intuitive approach for our clustering objectives.\n\nThe Euclidean distance between two p-dimensional points is given by the formula:\n\n$$\nd(x, y) = \\sqrt{(x_1 - y_1)^2 + (x_2 - y_2)^2 + \\cdots + (x_p - y_p)^2} = \\sqrt{(x - y)'(x - y)}\n$$\n\n**K-Means Clustering:** the process is composed of these three steps:\n\n1.  Partition the items into $K$ initial clusters.\n\n2.  Proceed through the list of items, assigning an item to the cluster whose centroid (mean) is nearest.\n    (Distance is usually computed using Euclidean distance with either standardized or standardized.) Recalculate the centroid for the cluster receiving the new item and for the cluster losing the item.\n\n3.  Repeat Step 2 until no more reassignments take place.\n    In practice, such as in R, this process might begin with a default of 10 iterations to ensure stability and convergence of clusters.\n\nTo determine the **optimal number of clusters (k)** in our analysis, we employed two methods: the Within-Sum-of-Squares (WSS) and the Gap Statistic.\nThe WSS method helps identify the elbow point where the addition of another cluster does not significantly improve the total variance within clusters.\nMeanwhile, the Gap Statistic compares the log-wss of our dataset against expected values under a null reference distribution of the data, providing a more robust estimation of the optimal k.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Optimal Number of Clusters](index_files/figure-html/fig-optimal-1.png){#fig-optimal width=672}\n:::\n:::\n\n\nBased on the analysis plot from @fig-optimal of the Total Within Sum of Square and the Gap Statistic plots, the optimal number of clusters for the data is recommended to be three.\nThe Elbow Method suggests a bend at three or four clusters, while the Gap Statistic clearly peaks and maximizes at three clusters, indicating the most suitable partitioning of the data.\n\nAfter identifying the optimal number of clusters as three through both the Elbow Method and the Gap Statistic, we proceed with the segmentation of the dataset to uncover distinct groupings and patterns.\nThis allows us to visualize and analyze the inherent structures and relationships within our data.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![K-Means Clustering](index_files/figure-html/fig-kmeans-1.png){#fig-kmeans width=672}\n:::\n:::\n\n\n1.  **Light Green Cluster (Circle): \"Defensores tradicionales\"**\n\nPlayers in this cluster, like Sebastian Olmedo and Arturo Ortiz, exhibit strong defensive capabilities, as evidenced by the cluster's alignment with key defensive actions such as tackles, interceptions, and blocks.\nThis group is indicative of players who excel in defensive duties, demonstrating a high degree of proficiency in preventing opposition attacks.\nThe outliers \"Andres Micolta Arroyo\" and \"Guido Pizarro\" may represent players with unique defensive styles or roles that differ from the standard defensive metrics, warranting closer examination.\n\n2.  **Red-Orange Cluster (Triangle): \"Defendores diferentes\"**\n\nThis cluster features players such as Carlos Salcedo, who are typically positioned further to the right, suggesting a distinct playing style.\nThese individuals may have fewer minutes on the pitch or adopt a defensive approach that doesn't primarily focus on tackles, interceptions, and blocks.\nAn example within this category is Hector Moreno of Monterrey, who exemplifies a style that balances traditional defensive duties with advanced playmaking and ball distribution skills.\nThe outlier \"Unai Bilbao\" suggests a player who might either excel exceptionally in these areas or possess a unique set of skills differing from the main group.\n\n3.  **Purple Cluster (Square): \"Defensores Versátiles\"**\n\nThis group, featuring Diego De Buen and Erik Lira, showcases versatility, balancing defensive responsibilities and some with the ability to support midfield and forward play, indicative of a modern, flexible center-back.\nThis adaptability makes them valuable for strategies requiring defensive solidity and midfield support.\n\n## Agglomerative Hierarchical Clustering\n\nAgglomerative Hierarchical Clustering is a popular method used in data analysis to group objects into clusters based on their similarities.\nStarting with each object in its own cluster, it iteratively combines the closest pairs into larger clusters until all objects are in a single group or a stopping criterion is met.\nThis bottom-up approach produces a dendrogram, a tree-like diagram that illustrates the series of merges and the hierarchical structure of the clusters.\n\nApplied the Ward.D2 approach, a specific type of Agglomerative Hierarchical Clustering, our main goal here is to reduce the sum of squared differences, also known as the 'loss of information,' across all clusters.\nThis reduction relies on calculating the squared Euclidean distances among the points in our dataset, a method that aligns with Ward's strategy to decrease the total variance within each cluster continuously.\nThis technique results in clusters that are more evenly distributed and meaningful, facilitating a better interpretation of the dataset's intrinsic structure since it generally forms clusters that are comparable in size.\n\nThe resulting dendrogram, illustrated below in @fig-Hierarchical, visualizes the hierarchical structure and the process of cluster formation.\nIt provides insights into the data's underlying patterns and relationships by showing how individual observations are grouped into clusters based on their similarities and how these clusters are combined into larger clusters as we move up the hierarchy.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Hierarchical Clustering](index_files/figure-html/fig-Hierarchical-1.png){#fig-Hierarchical width=672}\n:::\n:::\n\n\n**Observations:**\n\n1.  The light green cluster at the bottom includes players such as Sebastian Olmedo and Arturo Ortiz, indicating a group likely characterized by traditional defensive skills.\n\n2.  The purple cluster at the top, with players like Jesús Orozco and Igor Lichnovsky, suggesting these may be more versatile defenders who contribute both defensively and in initiating play, possibly indicating a balance between defensive robustness and ability to support midfield or offensive actions.\n\n3.  The red-orange cluster in the middle features players like Hector Moreno and Diego Reyes, could represent those who are perhaps less involved in direct defensive actions maybe because they spend less time on the pitch, but might play roles in ball distribution or possess other unique attributes distinguishing them from the purely defensive or hybrid players.\n\n## Conclusion\n\nIt is clear that different players fulfill their essential roles as center-back defenders.\nThe art of defending, often overshadowed by the allure of goals and assists, remains the cornerstone of every successful football team.\nNo team can dominate their league or excel in individual competitions without a strong defensive line.\nEmploying machine learning classification methods, including PCA, non-hierarchical k-means, and hierarchical clustering, holds profound significance in sports analytics, particularly in identifying similarities among players based on their defensive traits.\nThis approach can significantly aid teams in making informed decisions, especially during the transfer window, by identifying the ideal replacements that fit a specific defensive role, thereby enhancing team performance.\n\nHowever, it is crucial to acknowledge significant limitations.\nFor instance, there are skilled center-backs returning from injuries who have played minimally this season, which may influence their current performance levels as they regain their form.\nAdditionally, some teams may experience a poor start to the season but later find themselves on a winning streak.\nThe distinction between home and away games can also significantly impact player performance, with the venue potentially playing a crucial role in each match's outcome.\nFurthermore, matches against top-tier teams in the tournament can demand more from a player defensively, contrasting with games against weaker teams where the defensive workload might be substantially less.\n\nFuture enhancements for this project should consider several factors.\nInitially, the data was collected from the beginning of the tournament, from matchday 1 to matchday 9, which only represents the mid-point of the season.\nSince each season (Apertura and Clausura) comprises 17 matchdays, a more precise model could be developed with information spanning the entire season.\nAdditionally, incorporating data on full-backs, who also play defensive roles, could alter the classification narrative of players significantly.\nLastly, enriching the dataset with additional metrics such as possession and aerial duels could further refine the differentiation of player types in defensive positioning.\n\n## Acknowledgments\n\nI would like to express my sincere gratitude to the faculty members who guided me through my graduate studies in Applied Statistics at the Department of Mathematics and Statistics, California State University - Long Beach.\nSpecial acknowledgments to Dr. Sung Kim, Dr. Kagba Suaray, Dr. Olga Korosteleva, Dr. Rebecca Le, and Dr. Hojin Moon for their invaluable mentorship and support during my academic journey.\n\n## References\n\nJohnson, R. A., & Wichern, D. W.\n(2007).\n*Applied Multivariate Statistical Analysis*.\nPrentice Hall.\n\nNadir, N.\n(2021, September 21).\nAssessing NBA Player Similarity with Machine Learning.\n*Medium, Towards Data Science*.\n<https://towardsdatascience.com/which-nba-players-are-most-similar-machine-learning-provides-the-answers-r-project-b903f9b2fe1f>.\n\nOUKHOUYA, H.\n(2023, April 2).\nNBA Player Performance Analysis: PCA, Hierarchical Clustering, and K-Means Clustering.\n*RPubs*.\n<https://rpubs.com/HassanOUKHOUYA/NBA_Player_Performance_Analysis_PCA_Hierarchical_Clustering_and_K_Means_Clustering>.\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}