---
title: "Crime"
editor: visual
---

```{r}
library(tidyverse)
library(showtext)
library(lubridate)
library(janitor)
library(skimr)
library(glue)
library(ggtext)
library(scales)
library(ggTimeSeries)
library(ggh4x)
```

```{r}
# Add Google fonts
font_add_google("Oswald", family = "Oswald")
font_add_google("PT Serif", family = "Serif")

# Add local font
font_add("Font Awesome 6 Brands", here::here("fonts/otfs/Font Awesome 6 Brands-Regular-400.otf"))

# Automatically enable the use of showtext for all plots
showtext_auto()

# Set DPI for high-resolution text rendering
showtext_opts(dpi = 300)
```

```{r}
# Generate a social media caption with custom colors and font styling
social <- andresutils::social_caption(font_family = "Serif", icon_color = "#1F51FF", font_color = "grey45") 

# Construct the final plot caption with TidyTuesday details, data source, and social caption
cap <- paste0(
  "**Source**:  Los Angeles Police Department (LAPD) | **Graphic**: ", social
)
```

```{r}
# crime_raw <- read_csv("Data/crime_2025.csv") %>%
#   clean_names()
# 
# crime <- crime_raw %>%
#   mutate(
#     date = ymd_hms(date_occ),
#     year = year(date),
#     month = month(date),
#     day = day(date),
#     dow = wday(date, label = TRUE)
#   ) %>%
#   filter(
#     year %in% c(2020:2023))
# 
# skim(crime)
# 
# crime <- crime %>%
#   mutate(
#     vict_age = if_else(vict_age == 0, NA, vict_age)
#   ) %>%
#   select(
#     dr_no, date, year, month, dow, time_occ, area_name, crm_cd, crm_cd_desc, vict_age, vict_sex, vict_descent, premis_cd, premis_desc)
# 
# write_rds(crime, "Data/crime_2020_2023.rds")
```

```{r}
crime <- read_rds(here::here("Data/crime_2020_2023.rds"))
```


# Monthly Trends

```{r}
df <- crime %>%
  mutate(month = floor_date(as.Date(date), "month")) %>%  # ensure Date
  count(month, name = "n")

# Breaks every 3 months across the data range
brks <- seq(
  floor_date(min(df$month), "quarter"),
  ceiling_date(max(df$month), "quarter"),
  by = "3 months"
)

# Labels: show "Mon\nYear" only for Januaries; otherwise just "Mon"
lab_fun <- function(x) {
  ifelse(month(x) == 1, paste0(format(x, "%b"), "\n", format(x, "%Y")),
         format(x, "%b"))
}

high_point <- df %>%
  slice_max(n, n = 1, with_ties = FALSE)

low_point <- df %>%
  slice_min(n, n = 1, with_ties = FALSE)

point <- df %>%
  arrange(desc(month)) %>%
  slice(3)

# Compact formatter
compact_fmt <- label_number(
  accuracy = 0.1,                     # 1 decimal place
  scale_cut = cut_short_scale()       # K, M, B suffix
)

# Build highlight list
highlight <- bind_rows(
  mutate(
    high_point,
    label = paste0(
      format(month, "%b '%y"),
      "<br><span style='color:#1F51FF; font-size:8pt;'>",
      compact_fmt(n),
      "</span>"
    )
  ),
  mutate(
    low_point,
    label = paste0(
      format(month, "%b '%y"),
      "<br><span style='color:#1F51FF; font-size:8pt;'>",
      compact_fmt(n),
      "</span>"
    )
  ),
  mutate(
    point,
    label = paste0(
      format(month, "%b '%y"),
      "<br><span style='color:#1F51FF; font-size:8pt;'>",
      compact_fmt(n),
      "</span>"
    )
  )
)

y_max <- max(df$n, na.rm = TRUE)

df %>%
  ggplot(aes(x = month, y = n)) +
  geom_line(linewidth = 0.8, color = "#1F51FF") +
  geom_area(fill = "#1F51FF", alpha = 0.1) +
  geom_point(
    data = highlight,
    aes(x = month, y = n),
    shape = 23,
    color = "#1F51FF",
    fill = "#FFFFFF",
    size = 2.2,
    stroke = 0.8
  ) +
  geom_richtext(
    data = highlight,
    aes(x = month, y = n, label = label),
    vjust = -0.3,
    hjust = 0.5,
    color = "grey25",
    family = "Serif",
    fill = NA,
    # no background box
    label.color = NA,
    # no border
    size = 2.2
  ) +
  annotate(
    "text",
    x = as.Date("2020-03-15"),
    y = y_max * 0.60,
    label = "COVID-19\nRecession",
    family = "Serif",
    color = "#680b42",
    lineheight = 1.05,
    size = 2,
    hjust = 0,
    vjust = 2
  ) +
  annotate(
    "curve",
    x = as.Date("2020-04-15"),
    y = y_max * 0.57,
    xend = as.Date("2020-04-01"),
    yend = y_max * 0.75,
    curvature = -0.25,
    linetype = "dashed",
    linewidth = 0.5,
    colour = "#680b42",
    arrow = arrow(type = "closed", length = unit(0.08, "in"))
  ) +
  # Violent Crime Wave annotation
  annotate(
    "text",
    x = as.Date("2022-03-01"),
    # left of the spike
    y = y_max * 0.62,
    # vertical placement
    label = "Violent crime\npeak in 2022",
    family = "Serif",
    color = "#680b42",
    lineheight = 1.05,
    size = 2
  ) +
  annotate(
    "curve",
    x = as.Date("2022-03-01"),
    y = y_max * 0.7,
    # start near text
    xend = as.Date("2022-04-01"),
    yend = y_max * 0.95,
    # point to spike
    curvature = -0.2,
    linetype = "dashed",
    colour = "#680b42",
    arrow = arrow(type = "closed", length = unit(0.08, "in"))
  ) +
  labs(
    title = "Los Angeles Crime Hit a Low in 2021 Before Peaking in 2022 and Leveling Off",
    subtitle = "**Monthly Reported Incidents** [LAPD Data, Jan 2020 – Dec 2023]",
    x = NULL,
    y = "Incidents",
    caption = cap
  ) +
  scale_x_date(breaks = brks,
               labels = lab_fun,
               expand = c(0.01, 0.01)) +
  scale_y_continuous(labels = scales::comma, limits = c(0, 25000)) +
  theme_minimal(base_family = "Serif", base_size = 7) +
  theme(
    plot.title = element_textbox_simple(
      family = "Oswald",
      face = "bold",
      size = 14
    ),
    plot.subtitle = element_markdown(size = 6, margin = margin(t = 5)),
    plot.caption = element_textbox(
      size = 4.5,
      color = "grey45",
      hjust = 0,
      margin = margin(t = 10)
    ),
    plot.caption.position = "plot",
    plot.title.position = "plot",
    panel.grid = element_blank(),
    axis.ticks = element_line(color = "grey10", size = .3),
    plot.margin = margin(5, 5, 5, 5)
  )
```

```{r fig.height=4.5, fig.width=9}
top_10 <- crime %>%
  count(crm_cd_desc, name = "crimes") %>%
  arrange(desc(crimes)) %>%
  mutate(
    maxvalue = max(crimes) * 1.05,
    crm_cd_desc = str_to_title(crm_cd_desc)
  ) %>%
  slice(1:10)

# get top and 2nd to compute the gap
top_row  <- top_10 %>% slice_max(crimes, n = 1)
second   <- top_10 %>% slice_max(crimes, n = 2) %>% slice_tail(n = 1)
gap_lab  <- label_number(scale_cut = cut_short_scale(), accuracy = 0.1)(top_row$crimes - second$crimes)

annot_text <- glue(
  "<b><span style='color:#1F51FF'>Vehicle theft</span></b> is nearly
           <span style='color:#1F51FF'>25K</span> cases higher<br>
           than the <span style='color:grey70'>next most common crime</span>"
)

top_10 %>%
  mutate(is_max = crimes == max(crimes)) %>%
  ggplot(aes(
    x = reorder(crm_cd_desc, crimes),
    y = crimes,
    fill = is_max
  )) +
  geom_col() +
  geom_text(
    aes(
      y = maxvalue / 15,
      label = label_number(scale_cut = cut_short_scale(), accuracy = 0.1)(crimes),
      color = is_max
    ),
    size = 2,
    family = "Oswald",
    fontface = "bold"
  ) +
  coord_flip() +
  scale_color_manual(values = c("TRUE" = "#FFFFFF", "FALSE" = "#000000")) +
  scale_fill_manual(values = c("TRUE" = "#1F51FF", "FALSE" = "grey70")) +
  scale_y_continuous(expand = c(0.02, 0.02)) +
  annotate(
    "richtext",
    x = 5.5,
    # "Vehicle - Stolen" after str_to_title()
    y = top_row$crimes * 0.80,
    # place slightly to the right of the bar
    label = annot_text,
    hjust = 0.5,
    family = "Oswald",
    size = 2.2,
    fill = NA, label.color = NA
  ) +
  annotate(
  "segment",
  x = 6.2,                                # start at your textbox x
  y = top_row$crimes * 0.80,            # start a bit below the textbox
  xend = 9.3,           # end at the Vehicle - Stolen bar
  yend = top_row$crimes * 0.75,         # just shy of the bar top
  colour = "grey70",
  linewidth = 0.6,
  arrow = arrow(type = "closed", length = unit(0.18, "cm")),
  lineend = "round"
) +
  labs(
    title = "Most Common Crimes in Los Angeles",
    subtitle = "**Stolen vehicles top L.A.’s 10 most reported crimes** [LAPD Data, Jan 2020 – Dec 2023]",
    caption = cap,
    x = NULL,
    y = NULL
  ) +
  theme_minimal(base_family = "Oswald", base_size = 7) +
  theme(
    plot.title = element_text(size = 14, face = "bold"),
    plot.title.position = "plot",
    plot.subtitle = element_markdown(
      size = 6,
      margin = margin(t = 2, b = 5),
      family = "Serif"
    ),
    plot.caption = element_textbox(
      family = "Serif",
      size = 4.5,
      color = "grey45",
      hjust = 0,
      margin = margin(t = 5)
    ),
    plot.caption.position = "plot",
    axis.text.y = element_text(hjust = 1),
    axis.text.x = element_blank(),
    panel.grid = element_blank(),
    plot.margin = margin(5, 5, 5, 5),
    legend.position = "none"
  )

```

```{r}
names <- crime %>%
  filter(crm_cd_desc == "VEHICLE - STOLEN",
         year == 2023) %>%
  group_by(area_name) %>%
  count() %>%
  arrange(desc(n)) %>%
  ungroup() %>%
  slice(1:9) %>%
  pull(area_name)

dow_area <- crime %>%
  filter(crm_cd_desc == "VEHICLE - STOLEN",
         year == 2023,
         area_name %in% names) %>%
  group_by(dow, area_name) %>%
  count(name = "avg") %>%
  ungroup() %>%
  group_by(area_name) %>%
  mutate(is_max = avg == max(avg)) %>%
  ungroup()

dow_area %>%
  ggplot(aes(x = dow, y = avg, fill = is_max)) +
  geom_col() +
  geom_text(data = dow_area %>% filter(is_max == "TRUE"), aes(label = avg), family = "Oswald", color = "#FFFFFF", size = 1.8, vjust = 1.4) +
  facet_wrap2(vars(area_name), axes = "all") +
  scale_fill_manual(values = c("TRUE" = "#1F51FF", "FALSE" = "grey70")) +
  labs(
    title = "When Are Cars Stolen Most Often in Los Angeles?",
    subtitle = "**In 2023, vehicle thefts across LAPD divisions often peaked on Fridays and Saturdays.** [LAPD Data, Jan–Dec 2023]",
    caption = cap,
    x = NULL,
    y = NULL) +
  theme_minimal(base_family = "Oswald", base_size = 7) +
  theme(
    plot.title = element_text(size = 14, face = "bold"),
    plot.title.position = "plot",
    plot.subtitle = element_markdown(family = "Serif", size = 6, margin = margin(t = 2, b = 5)),
    plot.caption = element_textbox(
      family = "Serif",
      size = 4.5,
      color = "grey45",
      hjust = 0,
      margin = margin(t = 10)
    ),
    plot.caption.position = "plot",
    legend.position = "none",
    panel.grid.major.x = element_blank(),
    plot.margin = margin(5, 5, 5, 5)
  )
```

```{r}
daily <- crime %>%
  mutate(date = as_date(date)) %>%
  count(date, name = "incidents")

dtMonthLabels <- daily %>%
  mutate(
    WeekOfYear  = 1 + as.integer(strftime(date, "%W")),
    MonthOfYear = as.integer(strftime(date, "%m"))
  ) %>%
  group_by(MonthOfYear) %>%
  summarise(meanWeekOfYear = mean(WeekOfYear), .groups = "drop") %>%
  mutate(MonthOfYear = month.abb[MonthOfYear])

ggplot_calendar_heatmap(
  dtDateValue = daily,
  cDateColumnName = "date",
  cValueColumnName = "incidents",
  monthBorderSize = 1
) +
  scale_fill_gradient(low = "#FFFFFF", high = "#1F51FF",
                      guide = guide_colorbar(
                        direction = "horizontal",
                        barheight = unit(0.25, "cm"),
                        barwidth = unit(4, "cm"),
                        label.vjust = 0.5
                      )) +
  labs(
    title = "Los Angeles Crime",
    subtitle = "Daily incident counts",
    caption = cap,
    x = NULL,
    y = NULL,
    fill = NULL
  ) +
  facet_wrap(vars(Year),
             ncol = 1,
             axes = "all",
             strip.position = "left") +
  scale_x_continuous(
    breaks   = dtMonthLabels$meanWeekOfYear,
    labels   = dtMonthLabels$MonthOfYear,
    expand   = c(0, 0),
    position = "top"
  ) +
  theme_minimal(base_size = 7, base_family = "Serif") +
  theme(
    plot.title = element_text(family = "Oswald", face = "bold"),
    plot.caption = element_textbox(
      hjust = 0,
      size = 4.5,
      color = "grey45"
    ),
    plot.caption.position = "plot",
    legend.position = "bottom",
    strip.placement = "outside",
    strip.text = element_text(
      size = 10,
      family = "Oswald",
      color = "grey75"
    ),
    axis.ticks = element_blank(),
    panel.grid = element_blank(),
    plot.title.position = "plot",
    legend.ticks = element_blank(),
    plot.margin = margin(5, 5, 5, -10)
  ) 
```

